"""
Module 9 — Business Citation Builder (off-page SEO)
===================================================

For every directory in config/directories_au.yaml:

1. Build a NAP-consistent submission packet (name, address, phone, URL,
   categories, description, hours, social links, logo, photos) for your
   business.
2. Test whether the listing already exists by hitting the directory's
   search URL with your brand name.
3. Output a queue CSV of MISSING listings + a ready-to-paste packet for
   each directory.

NOTE: Free path — no aggregator API. A human (or VA) submits each.
If you upgrade to BrightLocal/Yext later, wire their API in publishers/.

Output:
  data/citation_packet.md                  (paste into each form)
  data/citation_status_<ts>.csv            (existing vs missing)
  data/citation_submission_queue_<ts>.csv  (ranked by priority)
"""
from __future__ import annotations

import re
from typing import Dict, List
from urllib.parse import quote_plus

import yaml

from config.settings import settings, DATA_DIR, ROOT
from utils.csv_writer import write_csv
from utils.http import get
from utils.logger import get_logger

log = get_logger("citations_biz")


def _load_directories() -> List[Dict]:
    path = ROOT / "config" / "directories_au.yaml"
    with open(path, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    return data.get("directories", [])


def _load_business() -> Dict:
    """Pull NAP data from keywords.yaml->entities->organization."""
    path = ROOT / "config" / "keywords.yaml"
    with open(path, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    return (data.get("entities") or {}).get("organization", {})


def _build_packet(biz: Dict) -> str:
    """Markdown packet a human can paste into any directory form."""
    addr = biz.get("address", {})
    contact = biz.get("contact", {})
    lines = [
        "# Citation Submission Packet — SecurityBlogs Australia",
        "",
        "**Copy/paste these fields into each directory form. Keep NAP IDENTICAL across every listing — even small variations hurt local SEO.**",
        "",
        "## Core NAP",
        f"- **Business Name**: {biz.get('legal_name', settings.site_name)}",
        f"- **Street Address**: {addr.get('street', '')}",
        f"- **Suburb / Locality**: {addr.get('locality', '')}",
        f"- **State**: {addr.get('region', '')}",
        f"- **Postcode**: {addr.get('postcode', '')}",
        f"- **Country**: Australia",
        f"- **Phone (AU format)**: {contact.get('phone', '')}",
        f"- **Email**: {contact.get('email', '')}",
        f"- **Website**: {settings.site_url}",
        "",
        "## Business categories",
        "- Primary: Security Services",
        "- Secondary: Security Guard Service, Alarm Monitoring, CCTV Installation, Security System Supplier",
        "",
        "## Short description (max 250 chars)",
        "> Australian security services covering CCTV monitoring, alarm response, AI surveillance and on-site guards for commercial, retail and construction sites — 24/7 monitoring centre, ASIAL-compliant.",
        "",
        "## Long description (max 750 chars)",
        "> SecurityBlogs delivers end-to-end security solutions across Australia: back-to-base alarm monitoring, rapid alarm response, AI-powered video surveillance, mobile patrols, construction-site security and retail loss prevention. Our Grade A1 monitoring centre operates 24/7/365 with ASIAL-certified operators and AS/NZS 2201 compliance. We serve Sydney, Melbourne, Brisbane, Perth, Adelaide, Canberra, Gold Coast and Newcastle.",
        "",
        "## Hours",
        "- Mon–Sun: 24 hours (monitoring); Office: Mon–Fri 8am–6pm AEST",
        "",
        "## Social profiles (sameAs)",
    ]
    for s in biz.get("same_as", []):
        lines.append(f"- {s}")
    lines += [
        "",
        "## Logo / photos",
        f"- Logo: {settings.site_url.rstrip('/')}/logo.png (square 1000x1000 PNG, transparent bg)",
        f"- Cover image: {settings.site_url.rstrip('/')}/cover.jpg (1920x1080 JPG)",
        "- 5–10 interior/exterior photos of monitoring centre and team",
        "",
        "## Service areas (enter each separately if directory allows)",
    ]
    for area in settings.service_areas:
        lines.append(f"- {area}, Australia")
    lines += [
        "",
        "## Founding year / ABN",
        f"- Founded: {biz.get('founding_date','').split('-')[0]}",
        "- ABN: (paste your ABN here)",
        "",
        "---",
        "*Generated by seo-bot citation_builder. Re-run any time NAP changes — the packet auto-regenerates from config/keywords.yaml.*",
    ]
    return "\n".join(lines)


def _check_existence(brand: str, search_url: str) -> bool:
    """Heuristic: fetch the directory's search results page and look for our brand."""
    url = search_url.format(q=quote_plus(brand))
    r = get(url, timeout=15)
    if not r or r.status_code != 200:
        return False
    text = r.text.lower()
    needle = brand.lower()
    domain = re.sub(r"^https?://(www\.)?", "", settings.site_url).rstrip("/").lower()
    return (needle in text) or (domain in text)


def run() -> Dict[str, str]:
    biz = _load_business()
    brand = biz.get("legal_name") or settings.site_name

    # 1. Packet
    packet_path = DATA_DIR / "citation_packet.md"
    packet_path.write_text(_build_packet(biz), encoding="utf-8")
    log.info(f"Packet -> {packet_path}")

    # 2. Existence + queue
    status_rows: List[Dict] = []
    queue_rows: List[Dict] = []
    for d in _load_directories():
        log.info(f"Checking: {d['name']}")
        exists = _check_existence(brand, d["search_url"])
        row = {
            "directory": d["name"],
            "category": d.get("category", ""),
            "priority": d.get("priority", 3),
            "free": d.get("free", True),
            "submit_url": d["submit_url"],
            "search_url": d["search_url"].format(q=quote_plus(brand)),
            "exists_heuristic": exists,
        }
        status_rows.append(row)
        if not exists:
            queue_rows.append(row)

    queue_rows.sort(key=lambda r: (r["priority"], 0 if r["free"] else 1))

    status_path = write_csv("citation_status", status_rows,
                            fieldnames=["directory", "category", "priority", "free",
                                        "submit_url", "search_url", "exists_heuristic"])
    queue_path = write_csv("citation_submission_queue", queue_rows,
                           fieldnames=["directory", "category", "priority", "free",
                                       "submit_url", "search_url", "exists_heuristic"])
    log.info(f"Status -> {status_path}\nQueue  -> {queue_path}")
    return {"packet": str(packet_path), "status": str(status_path), "queue": str(queue_path)}


if __name__ == "__main__":
    run()
